import { css, cx } from '@/styled-system/css'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const bodyClassname = cx(
    inter.className,
    css({ bg: 'gray.2', color: 'gray.12' }),
  )

  return (
    <html lang="en" className="dark">
      <body className={bodyClassname}>{children}</body>
    </html>
  )
}
